---
functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.

non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  
implicit:
  - У пользователя должна быть возможность зарегистрироваться/авторизоваться. Должна быть привязка к электронной почте.
  - При оформлении заказа у покупателя должна быть возможность оплатить товар. Т.е должен быть различные способы оплаты.
  - У пользователя должна быть возможность написать отзыв/отценить товар.
  - У интернет магазина должна быть контактная информация, что бы при каких то проблемах пользователь мог связяться с продавцом.
  - У пользователя должна быть возможность отследить свою покупку/ отследить прогресс отправки.
